### ISSUE TITLE
Tracker protocol unclear text

### ISSUE THREAD

**Issue by larroy** [jewel/clearskies#20]
"The ID and peer ID are combined into a single string separated by an "@" character, and sent as the "id" parameter."

It's not clear which ID is referring to. The ids should be clarified with an abbreviation consistent in the whole text.

**Comment by jewel** [comment]
You're right, during the development of the spec the IDs have morphed a number of times, and are confusing.  The tracker protocol is where it becomes the most unmanageable.  It's probably time to make the tracker request a JSON post, so that we can make things amply clear.  Thank you for bringing this to my attention, I will fix it.

**Comment by jewel** [comment]
I have rewritten the tracker protocol section, which is more explicit about what ID means.
