### ISSUE TITLE
Local IP tracking, broadcast limitations

### ISSUE THREAD

**Issue by larroy** [jewel/clearskies#21]
The broadcast mechanism is not sufficient for networks which have different disjoint broadcast domains. The peer should report to the tracker it's list of known local addresses, so other peers in the same private network can readily find them, even their broadcast domains are different.

**Comment by jewel** [comment]
Good point, and there are other reasons to let clients self-report their IP address, such that it lets them send both an IPv6 and an IPv4 address if both are known, or multiple addresses if they are multi-homed.  The reason I didn't include a mechanism for this originally is that it would allow a node to direct a tiny DDOS attack against any IP address and port.  However, now that I think about it, that's not a very big concern in practice, since there would have to be a widely subscribed public share (which is not the use case clearskies is optimized for), the implementations would have to ignore the recommendation to limit the number of active peers per share, and the receiving socket is expected to send a message first.

I will add this to the tracker protocol.  Thanks for opening the issue!

**Comment by jewel** [comment]
Addresses are now self-reported as of the latest tracker protocol update.
