### ISSUE TITLE
Wire protocol chunk size

### ISSUE THREAD

**Issue by larroy** [jewel/clearskies#22]
Size of chunks in the wire protocol be limited to a maximum to avoid DOS attacks on clients that reserve a buffer with the size of the chunk.

**Comment by jewel** [comment]
Good call.  What limit do you think would be acceptable?  For languages like ruby it'd be nice to have it be fairly large, like a megabyte, so that the ruby overhead for stream processing is minimal (I'm thinking about gigabit LAN transfers).  An implementation that didn't want to dedicate that much memory for each active transfer could use a smaller buffer and read each chunk in multiple pieces.

In any case, we should definitely add a limit in the spec just so that implementations take it into consideration, instead of how it is right now where a naive implementation might send a 10GB file in one chunk, which could overflow a 32-bit int on the other end.

As an aside, the original wire protocol didn't do chunking at all, but I added it so that extensions would be able to send large binary messages without knowing the total size of the message it was sending.  For example, this is critical for the rsync extension.

**Comment by larroy** [comment]
I think the design of the chunking protocol is quite nice, and I like the idea of the ! and $ characters with the json header and the data following.

About the limit in the end it has to be an arbitrary decision beyond a point where the overhead is quite small. I'd say above 2^24 16Mb doesn't make much sense anymore. Maybe it would be nice to recommend in the spec a buffer size of 1Mb or 4Mb for normal transfers...
