### ISSUE TITLE
Parsing JSON before authentication opens for certain vulnerabilities

### ISSUE THREAD

**Issue by calmh** [jewel/clearskies#31]
Very large JSON objects in the handshake could consume non-trivial amounts of memory and CPU on the server side.

**Comment by jewel** [comment]
Thanks @calmh!  You're exactly right.  I'm actually in the process of changing the spec so that it uses TLS-SRP mode instead of TLS-PSK.  As a part of that change, I intend to move _all_ communication to be after the TLS handshake.  There is a [thread on the mailing list](https://groups.google.com/d/msg/clearskies-dev/PtBhMr1WWB4/Oy2_2OTIvmEJ) where this is discussed in more detail.  I hope to add this to the `protocol_cleanup` branch this week.

I will leave this issue open in the interim until it's definitely solved.

**Comment by calmh** [comment]
Yep, not doing anything until an authenticated TLS connection is up is for sure the safer bet.

**Comment by jewel** [comment]
This is fixed in the latest version of the protocol.
