### ISSUE TITLE
Need to list required ports for firewalls

### ISSUE THREAD

**Issue by jpjp** [jewel/clearskies#32]
Could you add the required ports for opening up a firewall somewhere?

**Comment by jewel** [comment]
The default behavior is to attempt to use UPnP and UDP hole punching to make a connection without requiring the user to open a port.  Because of this, there is no default listening port (it is chosen at random on each launch).

I'm also planning on adding TURN support, for the worst-case scenario where no direct connection is possible.

We need to add the status of UPnP and hole punching to the `status` command, so that users can know whether or not it is successful.

Advanced users can force the port to a specific value via the `-p` (or `--listen-port`) option.

**Comment by jpjp** [comment]
Ah thanks. I don't think this is documented in --help.

Just trying to use this right now, and it doesn't seem to work with NATting very well. Is there some documentation somewhere?

**Comment by larroy** [comment]
what's TURN? any pointers?

**Comment by snake66** [comment]
https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT

**Comment by jewel** [comment]
@jpjp There isn't any other documentation at the moment, but there definitely should be.  I also need to set up some integration tests using [VDE](http://wiki.v2.cs.unibo.it/wiki/index.php/Main_Page) that simulate different NATs so that I can work out some remaining issues with the uTP code.

Note that the C++ implementation is going to integrate libutp which should be more robust than what the home-grown uTP implementation in the ruby code.

If you start the daemon with --listen-port 1234, and then forward port 1234 on your firewall to that computer, it should be able to connect.  This only needs to be done on one of the peers.  If it doesn't work, do you want to open a separate issue with the logs from both computers attached?

**Comment by jpjp** [comment]
My test was two hosts in the internal network. They don't see each other presumably because they are getting the external ip of the router. syncthing handles this with local broadcast discovery.

**Comment by jewel** [comment]
The ruby code does broadcast discovery too, on both IPv4 and IPv6, so I'm surprised that's not working.  It sounds like you've found a bug, I'll see if I can reproduce it.

**Comment by GitMoDu** [comment]
This is awesome, the one downfall of BTSync is most public WiFi block (or at least attempt to) torrent protocol traffic. One thing they can't block is when the traffic is wrapped in SSL (I actually researched this).

**Comment by jewel** [comment]
The ruby implementation has been moved to another repository.  I've put a placeholder there for this issue: https://github.com/jewel/clearskies-ruby/issues/1.
