### ISSUE TITLE
Silly Question

### ISSUE THREAD

**Issue by djblue** [jewel/clearskies#4]
Is there any documentation on how to use the cli? I can't seem to get the daemon to start. Every time I try to run any of the commands I get 'Daemon not running'. I ran the tests and I get:

test_0004_should detect deleted files(Scanner::finds files)
test_0002_should detect new files(Scanner::finds files)

I am not sure what to do. I am not too familiar with ruby but I would still like to contribute.

**Comment by jewel** [comment]
Hello @djblue!  It's not a silly question.  We've just barely gotten it to the point where it syncs things, and haven't added any documentation about how to use it yet.

Normally you'd do "clearskies start", but it looks like it doesn't work.  I've been doing "clearskies debug", which starts the daemon in the foreground so that you can see logging messages.  I'll fix "start" and also add a note to the "Daemon not running" message that tells the user to do the same.

It looks like the tests fail if you don't have the rb-inotify gem installed.  It's not meant to be a hard dependency, since we are planning to port to Windows.  (It falls back to rescanning the directory periodically, but that doesn't happen before the test times out.)  I'll adjust the test so that it reacts to the situation accordingly.

I'll try and get all these things done over the weekend.

Your contributions are welcome.  Feel free to email me at clearskies@stevenjewel.com if you'd like to discuss things without having to open an issue.

**Comment by jewel** [comment]
I've updated the documentation which I hope will help new users in the future.
