### ISSUE TITLE
Unclear what to do when access code or club is not found

### ISSUE THREAD

**Issue by onionjake** [jewel/clearskies#51]
In core.md:

> The server then uses the username to see if it has a corresponding access code or club. If it does, it completes the connection. The password or key is given to the TLS library as lowercase hexadecimal.

It isn't clear what is supposed to happen if it does not have a corresponding access code or club.

**Comment by jewel** [comment]
In theory, this would only happen due to a race condition, where the club was removed from a client but one of its peers is still trying to connect.  If possible, we should respond with the [unknown_psk_identity](http://tools.ietf.org/html/rfc5054#section-2.9) error.

Handling this condition would be similar to handling connection errors.  For example, we should retry with a decaying period.  If the source of the peer was the tracker, I'd expect that the tracker's entry would be removed soon.

**Comment by onionjake** [comment]
Couldn't it also happen if access codes were time based?

**Comment by jewel** [comment]
Once the time has expired the peer should deregister the access code with the tracker, so it should also be a race condition.
