### ISSUE TITLE
minor passphrase clarifications

### ISSUE THREAD

**Issue by grgz** [jewel/clearskies#7]
The Password section starts with "Instead of generating the master key".  It might be clearer to say "Instead of generating a random read-write PSK".  (I don't think the term "master key" is used anywhere else?)

Second, "The SHA256 algorithm is applied twenty million times to generate the 256-bit encryption key".  Does this mean the read-write PSK?  Is the PSK actually 256-bits in the passphrase case, but 128-bits for random keys?

Also, I was thinking it might be good practice for users to include a unique(ish) identifier as part of their passphrase, such as an email or domain name, in order to avoid accidentally colliding with someone else's passphrase.

This is looking pretty cool -- keep it up!
-greg

**Comment by jewel** [comment]
Wow, thank you for reading over the spec so closely!  You're right on all counts.  I believe at one time the PSK was going to be 256-bit, so that is a mistake.  We'd want to use the first 128-bits of the 20-millionth hash as the PSK.

That's excellent advice about advising the users to make the passphrase unique.

I will make your recommended corrections.  For what it's worth, I actually intend to rework the master passphrase to work more like an access code, but with code spreading, so that the user can add or remove one at any time.  (This is one of the known issues listed at the very bottom of the spec.)

**Comment by jewel** [comment]
I believe this has been addressed in the current version of the spec, which avoids ever using SHA256 as a password stretching method.  (It uses TLS-SRP mode instead.)
